### ISSUE TITLE
按照你给的教程写的dockerfile

### ISSUE THREAD

**Issue by jkjoy** [RandallAnjie/moments#3]
[package.json](https://github.com/RandallAnjie/moments/blob/master/package.json)
缺少
```
"defu": "^6.1.0",
"ofetch": "^1.3.4"
```
dockerfile
```
FROM debian:latest
RUN apt update && apt install -y curl libheif-examples  git
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - 
RUN apt install  -y nodejs
RUN mkdir -p /opt/moments && cd /opt/moments && git clone https://github.com/RandallAnjie/moments.git && cd moments && npm install
RUN echo | npx prisma migrate dev
RUN npm run build
RUN curl -o data/db.sqlite https://randallanjie.com/download/db.sqlite
EXPOSE 3000
CMD [ "node", "/opt/moments/moments/.output/server/index.mjs" ]
```
镜像大小1.6G
redis 重新拉取一个 
redis-server

**Comment by jkjoy** [comment]
docker-compose.yaml
```yaml
services:
  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - moments_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data
  web:
    image: jkjoy/moments
    restart: always
    #env_file: .env
    networks:
      - moments_network
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - redis
    volumes:
      - ./data:/app/data/
networks:
  moments_network:
```
